# Generated by Django 4.0.6 on 2022-07-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='user',
        ),
    ]
