# Generated by Django 4.0.6 on 2022-07-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0002_remove_gamereview_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameReview',
        ),
    ]
