# Generated by Django 4.0.6 on 2022-07-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0003_delete_gamereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описання')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelibs.game', verbose_name='Гра')),
            ],
            options={
                'verbose_name': 'Ігровий відгук',
                'verbose_name_plural': 'Ігрові відгуки',
            },
        ),
    ]
