# Generated by Django 4.0.6 on 2022-07-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0004_gamereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamelibs.profile'),
        ),
    ]
