# Generated by Django 4.0.6 on 2022-07-20 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0006_alter_gamereview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публікації'),
        ),
    ]
