# Generated by Django 4.0.6 on 2022-07-20 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamelibs', '0007_gamereview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описання')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публікації')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelibs.post', verbose_name='Гра')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук поста',
                'verbose_name_plural': 'Відгуки постів',
            },
        ),
    ]
