# Generated by Django 4.0.6 on 2022-07-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0008_postreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereview',
            options={'ordering': ['-id'], 'verbose_name': 'Ігровий відгук', 'verbose_name_plural': 'Ігрові відгуки'},
        ),
        migrations.AlterModelOptions(
            name='postreview',
            options={'ordering': ['-id'], 'verbose_name': 'Відгук поста', 'verbose_name_plural': 'Відгуки постів'},
        ),
    ]
