# Generated by Django 4.0.6 on 2022-07-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0011_remove_reviews_loc_alter_reviews_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='games',
        ),
        migrations.AddField(
            model_name='post',
            name='games',
            field=models.ForeignKey(help_text='Вказати тільки одну гру!', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamelibs.game', verbose_name='Вкажіть гру'),
        ),
    ]
