# Generated by Django 4.0.6 on 2022-07-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0013_remove_post_games_post_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='games',
            new_name='game',
        ),
    ]
