# Generated by Django 4.0.6 on 2022-07-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0014_rename_games_post_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='game',
            new_name='games',
        ),
    ]
