# Generated by Django 4.0.6 on 2022-07-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0015_rename_game_post_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description_small',
        ),
    ]
