# Generated by Django 4.0.6 on 2022-07-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0017_ratingstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelibs.game', verbose_name='гра')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelibs.ratingstar', verbose_name='зірка')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
