# Generated by Django 4.0.6 on 2022-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0019_alter_rating_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
