# Generated by Django 4.0.6 on 2022-07-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0020_delete_rating_delete_ratingstar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
