# Generated by Django 4.0.6 on 2022-07-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0022_rename_review_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
