# Generated by Django 4.0.6 on 2022-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibs', '0023_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=200, verbose_name='Повідомлення')),
                ('draft', models.BooleanField(default=True, verbose_name='Чернетка')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
